insert into address(city, country, postal_code, street, user_id ) values ('Bruxelles', 'Belgique', '75500', '10 Avenue de Bruxelles', 1);
insert into address(city, country, postal_code, street, user_id ) values ('Amsterdam', 'Pays-Bas', '42000', '42 Boulevard de la Nature', 1);
insert into address(city, country, postal_code, street, user_id ) values ('Ivry-Sur-Seine', 'France', '94200', '10 Rue Maurice Grandcoing', 1);
insert into address(city, country, postal_code, street, user_id ) values ('Paris', 'France', '75000', '12 Avenue de Paris', 2);
insert into address(city, country, postal_code, street, user_id ) values ('Cannes', 'France', '06200', '13 Avenue de la joie de vivre', 2);
insert into address(city, country, postal_code, street, user_id ) values ('Ivry-Sur-Seine', 'France', '94200', '10 Rue Maurice Grandcoing', 3);
insert into address(city, country, postal_code, street, user_id ) values ('Paris', 'France', '75000', '12 Rue de la Liberté', 3);
insert into address(city, country, postal_code, street, user_id ) values ('Ivry-Sur-Seine', 'France', '94200', '8 Allée Gagarine', 4);
insert into address(city, country, postal_code, street, user_id ) values ('Ivry-Sur-Seine', 'France', '94200', '80 Avenue Molière', 5);
insert into address(city, country, postal_code, street, user_id ) values ('Paris', 'France', '75000', '10 Avenue de France', 5);